export type EmojiCategory = {
  id: string;
  label: string;
  icon: string;
};

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  { id: "smileys", label: "Smileys", icon: "😀" },
  { id: "people", label: "People", icon: "👋" },
  { id: "animals", label: "Nature", icon: "🐶" },
  { id: "food", label: "Food", icon: "🍕" },
  { id: "travel", label: "Travel", icon: "✈️" },
  { id: "activities", label: "Activity", icon: "⚽" },
  { id: "objects", label: "Objects", icon: "💡" },
  { id: "symbols", label: "Symbols", icon: "❤️" },
  { id: "flags", label: "Flags", icon: "🏳️" },
];

const RANGES: [number, number][] = [
  [0x231a, 0x231b],
  [0x23e9, 0x23f3],
  [0x23f8, 0x23fa],
  [0x25aa, 0x25ab],
  [0x25b6, 0x25b6],
  [0x25c0, 0x25c0],
  [0x25fb, 0x25fe],
  [0x2600, 0x27bf],
  [0x2934, 0x2935],
  [0x2b05, 0x2b07],
  [0x2b1b, 0x2b1c],
  [0x2b50, 0x2b50],
  [0x2b55, 0x2b55],
  [0x3030, 0x3030],
  [0x303d, 0x303d],
  [0x3297, 0x3297],
  [0x3299, 0x3299],
  [0x1f004, 0x1f004],
  [0x1f0cf, 0x1f0cf],
  [0x1f170, 0x1f171],
  [0x1f17e, 0x1f17f],
  [0x1f18e, 0x1f18e],
  [0x1f191, 0x1f19a],
  [0x1f1e6, 0x1f1ff],
  [0x1f201, 0x1f202],
  [0x1f21a, 0x1f21a],
  [0x1f22f, 0x1f22f],
  [0x1f232, 0x1f23a],
  [0x1f250, 0x1f251],
  [0x1f300, 0x1faff],
];

const EXTRA = [
  "#️⃣",
  "*️⃣",
  "0️⃣",
  "1️⃣",
  "2️⃣",
  "3️⃣",
  "4️⃣",
  "5️⃣",
  "6️⃣",
  "7️⃣",
  "8️⃣",
  "9️⃣",
  "❤️",
  "🧡",
  "💛",
  "💚",
  "💙",
  "💜",
  "🖤",
  "🤍",
  "🤎",
  "💔",
  "❣️",
  "💕",
  "💞",
  "💓",
  "💗",
  "💖",
  "💘",
  "💝",
  "✨",
  "⭐",
  "🌟",
  "⚡",
  "☀️",
  "☁️",
  "☂️",
  "❄️",
  "✈️",
  "☎️",
  "✂️",
  "✏️",
  "✒️",
  "✔️",
  "✖️",
  "➡️",
  "⬅️",
  "⬆️",
  "⬇️",
  "🏳️‍🌈",
  "🏳️‍⚧️",
  "🏴‍☠️",
  "👨‍💻",
  "👩‍💻",
  "👨‍⚕️",
  "👩‍⚕️",
  "👨‍🏫",
  "👩‍🏫",
  "👨‍🍳",
  "👩‍🍳",
  "👨‍🚀",
  "👩‍🚀",
  "🧑‍💻",
  "🧑‍🚀",
  "👨‍👩‍👧‍👦",
  "👩‍❤️‍👨",
  "👨‍❤️‍👨",
  "👩‍❤️‍👩",
];

const ISO_FLAGS = [
  "AD","AE","AF","AG","AI","AL","AM","AO","AQ","AR","AS","AT","AU","AW","AX","AZ",
  "BA","BB","BD","BE","BF","BG","BH","BI","BJ","BL","BM","BN","BO","BQ","BR","BS",
  "BT","BV","BW","BY","BZ","CA","CC","CD","CF","CG","CH","CI","CK","CL","CM","CN",
  "CO","CR","CU","CV","CW","CX","CY","CZ","DE","DJ","DK","DM","DO","DZ","EC","EE",
  "EG","EH","ER","ES","ET","EU","FI","FJ","FK","FM","FO","FR","GA","GB","GD","GE",
  "GF","GG","GH","GI","GL","GM","GN","GP","GQ","GR","GS","GT","GU","GW","GY","HK",
  "HM","HN","HR","HT","HU","ID","IE","IL","IM","IN","IO","IQ","IR","IS","IT","JE",
  "JM","JO","JP","KE","KG","KH","KI","KM","KN","KP","KR","KW","KY","KZ","LA","LB",
  "LC","LI","LK","LR","LS","LT","LU","LV","LY","MA","MC","MD","ME","MF","MG","MH",
  "MK","ML","MM","MN","MO","MP","MQ","MR","MS","MT","MU","MV","MW","MX","MY","MZ",
  "NA","NC","NE","NF","NG","NI","NL","NO","NP","NR","NU","NZ","OM","PA","PE","PF",
  "PG","PH","PK","PL","PM","PN","PR","PS","PT","PW","PY","QA","RE","RO","RS","RU",
  "RW","SA","SB","SC","SD","SE","SG","SH","SI","SJ","SK","SL","SM","SN","SO","SR",
  "SS","ST","SV","SX","SY","SZ","TC","TD","TF","TG","TH","TJ","TK","TL","TM","TN",
  "TO","TR","TT","TV","TW","TZ","UA","UG","UM","US","UY","UZ","VA","VC","VE","VG",
  "VI","VN","VU","WF","WS","XK","YE","YT","ZA","ZM","ZW",
];

const KEYWORDS: Record<string, string> = {
  "😀": "grin smile happy",
  "😃": "smile happy",
  "😄": "smile happy laugh",
  "😁": "grin smile",
  "😆": "laugh happy",
  "😅": "sweat smile nervous",
  "🤣": "rofl laugh",
  "😂": "joy tears laugh cry",
  "🙂": "smile slight",
  "😉": "wink",
  "😊": "blush smile happy",
  "😇": "angel innocent",
  "🥰": "love hearts smile",
  "😍": "love heart eyes",
  "🤩": "star struck",
  "😘": "kiss love",
  "😗": "kiss",
  "😚": "kiss",
  "😋": "yum tasty",
  "😛": "tongue",
  "😜": "wink tongue",
  "🤪": "zany crazy",
  "😝": "tongue",
  "🤗": "hug",
  "🤭": "oops secret",
  "🤫": "shush quiet",
  "🤔": "think thinking",
  "😐": "neutral",
  "😑": "expressionless",
  "😶": "silent",
  "😏": "smirk",
  "😒": "unamused",
  "🙄": "eyeroll eyes",
  "😬": "grimace awkward",
  "😔": "sad pensive",
  "😪": "sleepy",
  "🤤": "drool",
  "😴": "sleep zzz",
  "😷": "mask sick",
  "🤒": "sick fever",
  "🤕": "hurt injury",
  "🤢": "sick nauseous",
  "🤮": "vomit",
  "🥵": "hot",
  "🥶": "cold",
  "🥴": "woozy",
  "😵": "dizzy",
  "🤯": "mind blown",
  "🤠": "cowboy",
  "🥳": "party celebrate",
  "😎": "cool sunglasses",
  "🤓": "nerd glasses",
  "🧐": "monocle",
  "😕": "confused",
  "😟": "worried",
  "🙁": "frown sad",
  "😮": "surprised wow",
  "😯": "hushed",
  "😲": "astonished",
  "😳": "flushed embarrassed",
  "🥺": "pleading puppy",
  "😢": "cry sad tear",
  "😭": "sob cry",
  "😱": "scream fear",
  "😨": "fear",
  "😰": "anxious sweat",
  "😥": "disappointed relief",
  "😓": "sweat",
  "😞": "disappointed sad",
  "😖": "confounded",
  "😣": "persevere",
  "😩": "weary tired",
  "😫": "tired",
  "🥱": "yawn",
  "😤": "triumph huff",
  "😡": "angry mad",
  "😠": "angry",
  "🤬": "swear curse",
  "😈": "devil smile",
  "👿": "imp angry devil",
  "💀": "skull dead",
  "☠️": "skull crossbones",
  "💩": "poop",
  "🤡": "clown",
  "👹": "ogre",
  "👺": "goblin",
  "👻": "ghost",
  "👽": "alien",
  "👾": "invader",
  "🤖": "robot",
  "😺": "cat smile",
  "🙈": "see no evil monkey",
  "🙉": "hear no evil monkey",
  "🙊": "speak no evil monkey",
  "💋": "kiss lips",
  "👋": "wave hello bye",
  "🤚": "hand",
  "🖐️": "hand fingers",
  "✋": "hand stop",
  "🖖": "vulcan",
  "👌": "ok",
  "🤌": "pinched",
  "✌️": "peace victory",
  "🤞": "luck fingers crossed",
  "🤟": "love you",
  "🤘": "rock horns",
  "🤙": "call",
  "👈": "left point",
  "👉": "right point",
  "👆": "up point",
  "👇": "down point",
  "☝️": "up",
  "👍": "thumbs up yes like",
  "👎": "thumbs down no",
  "✊": "fist",
  "👊": "punch",
  "🤛": "fist left",
  "🤜": "fist right",
  "👏": "clap applause",
  "🙌": "raise hands hooray",
  "👐": "open hands",
  "🤲": "palms",
  "🤝": "handshake deal",
  "🙏": "pray thanks please",
  "✍️": "write",
  "💅": "nails",
  "🤳": "selfie",
  "💪": "muscle strong",
  "🦾": "mechanical arm",
  "🦵": "leg",
  "🦶": "foot",
  "👂": "ear",
  "👃": "nose",
  "🧠": "brain",
  "👀": "eyes look",
  "👁️": "eye",
  "👅": "tongue",
  "👄": "mouth lips",
  "👶": "baby",
  "👧": "girl",
  "👦": "boy",
  "👩": "woman",
  "👨": "man",
  "🧑": "person",
  "👵": "old woman",
  "👴": "old man",
  "🙍": "frown",
  "🙎": "pout",
  "🙅": "no",
  "🙆": "ok gesture",
  "💁": "sassy tip",
  "🙋": "raise hand",
  "🧏": "deaf",
  "🙇": "bow",
  "🤦": "facepalm",
  "🤷": "shrug",
  "👮": "police",
  "🕵️": "detective",
  "💂": "guard",
  "🥷": "ninja",
  "👷": "worker construction",
  "🤴": "prince",
  "👸": "princess",
  "👳": "turban",
  "👲": "gua pi mao",
  "🧕": "hijab",
  "🤵": "tuxedo",
  "👰": "bride",
  "🤰": "pregnant",
  "🤱": "nursing",
  "👼": "angel baby",
  "🎅": "santa",
  "🤶": "mrs claus",
  "🦸": "hero",
  "🦹": "villain",
  "🧙": "mage wizard",
  "🧚": "fairy",
  "🧛": "vampire",
  "🧜": "mermaid",
  "🧝": "elf",
  "🧞": "genie",
  "🧟": "zombie",
  "💆": "massage",
  "💇": "haircut",
  "🚶": "walk",
  "🧍": "stand",
  "🧎": "kneel",
  "🏃": "run",
  "💃": "dance woman",
  "🕺": "dance man",
  "🕴️": "levitate",
  "👯": "dancers",
  "🧖": "sauna",
  "🧗": "climb",
  "🤺": "fence",
  "🏇": "horse race",
  "⛷️": "ski",
  "🏂": "snowboard",
  "🏌️": "golf",
  "🏄": "surf",
  "🚣": "row",
  "🏊": "swim",
  "⛹️": "ball",
  "🏋️": "lift weights",
  "🚴": "bike",
  "🚵": "mountain bike",
  "🤸": "cartwheel",
  "🤼": "wrestle",
  "🤽": "water polo",
  "🤾": "handball",
  "🤹": "juggle",
  "🧘": "yoga lotus",
  "🛀": "bath",
  "🛌": "sleep bed",
  "🐶": "dog puppy",
  "🐱": "cat kitten",
  "🐭": "mouse",
  "🐹": "hamster",
  "🐰": "rabbit bunny",
  "🦊": "fox",
  "🐻": "bear",
  "🐼": "panda",
  "🐨": "koala",
  "🐯": "tiger",
  "🦁": "lion",
  "🐮": "cow",
  "🐷": "pig",
  "🐸": "frog",
  "🐵": "monkey",
  "🐔": "chicken",
  "🐧": "penguin",
  "🐦": "bird",
  "🐤": "chick",
  "🦆": "duck",
  "🦅": "eagle",
  "🦉": "owl",
  "🦇": "bat",
  "🐺": "wolf",
  "🐗": "boar",
  "🐴": "horse",
  "🦄": "unicorn",
  "🐝": "bee",
  "🐛": "bug",
  "🦋": "butterfly",
  "🐌": "snail",
  "🐞": "ladybug",
  "🐜": "ant",
  "🦟": "mosquito",
  "🦗": "cricket",
  "🕷️": "spider",
  "🦂": "scorpion",
  "🐢": "turtle",
  "🐍": "snake",
  "🦎": "lizard",
  "🦖": "t-rex dinosaur",
  "🦕": "dinosaur",
  "🐙": "octopus",
  "🦑": "squid",
  "🦐": "shrimp",
  "🦞": "lobster",
  "🦀": "crab",
  "🐡": "blowfish",
  "🐠": "fish tropical",
  "🐟": "fish",
  "🐬": "dolphin",
  "🐳": "whale",
  "🐋": "whale",
  "🦈": "shark",
  "🐊": "crocodile",
  "🐅": "tiger",
  "🐆": "leopard",
  "🦓": "zebra",
  "🦍": "gorilla",
  "🦧": "orangutan",
  "🐘": "elephant",
  "🦛": "hippo",
  "🦏": "rhino",
  "🐪": "camel",
  "🐫": "camel",
  "🦒": "giraffe",
  "🦘": "kangaroo",
  "🦬": "bison",
  "🐃": "buffalo",
  "🐂": "ox",
  "🐄": "cow",
  "🐎": "horse",
  "🐖": "pig",
  "🐏": "ram",
  "🐑": "sheep",
  "🦙": "llama",
  "🐐": "goat",
  "🦌": "deer",
  "🐕": "dog",
  "🐩": "poodle",
  "🦮": "guide dog",
  "🐈": "cat",
  "🪶": "feather",
  "🐓": "rooster",
  "🦃": "turkey",
  "🦤": "dodo",
  "🦚": "peacock",
  "🦜": "parrot",
  "🦢": "swan",
  "🦩": "flamingo",
  "🕊️": "dove peace",
  "🐇": "rabbit",
  "🦝": "raccoon",
  "🦨": "skunk",
  "🦡": "badger",
  "🦫": "beaver",
  "🦦": "otter",
  "🦥": "sloth",
  "🐁": "mouse",
  "🐀": "rat",
  "🐿️": "chipmunk",
  "🦔": "hedgehog",
  "🐾": "paw",
  "🐉": "dragon",
  "🐲": "dragon face",
  "🌵": "cactus",
  "🎄": "christmas tree",
  "🌲": "tree evergreen",
  "🌳": "tree",
  "🌴": "palm",
  "🪵": "wood",
  "🌱": "seedling",
  "🌿": "herb leaf",
  "☘️": "shamrock",
  "🍀": "clover luck",
  "🎍": "bamboo",
  "🪴": "plant pot",
  "🎋": "tanabata",
  "🍃": "leaf wind",
  "🍂": "leaf fallen",
  "🍁": "maple",
  "🍄": "mushroom",
  "🐚": "shell",
  "🪨": "rock",
  "🌾": "rice",
  "💐": "bouquet",
  "🌷": "tulip",
  "🌹": "rose",
  "🥀": "wilted",
  "🌺": "hibiscus",
  "🌸": "cherry blossom",
  "🌼": "blossom",
  "🌻": "sunflower",
  "🌞": "sun face",
  "🌝": "full moon face",
  "🌛": "moon",
  "🌜": "moon",
  "🌚": "new moon face",
  "🌕": "full moon",
  "🌖": "moon",
  "🌗": "moon",
  "🌘": "moon",
  "🌑": "new moon",
  "🌒": "moon",
  "🌓": "moon",
  "🌔": "moon",
  "🌙": "crescent moon",
  "🌎": "earth americas world",
  "🌍": "earth africa europe world",
  "🌏": "earth asia world",
  "🪐": "saturn planet",
  "💫": "dizzy star",
  "⭐": "star",
  "🌟": "glowing star",
  "✨": "sparkles",
  "⚡": "lightning zap",
  "☄️": "comet",
  "💥": "boom collision",
  "🔥": "fire flame lit",
  "🌪️": "tornado",
  "🌈": "rainbow",
  "☀️": "sun sunny",
  "🌤️": "sun cloud",
  "⛅": "cloud sun",
  "☁️": "cloud",
  "🌧️": "rain",
  "⛈️": "storm",
  "🌩️": "lightning cloud",
  "🌨️": "snow",
  "❄️": "snowflake cold",
  "☃️": "snowman",
  "⛄": "snowman",
  "🌬️": "wind",
  "💨": "dash wind",
  "💧": "droplet water",
  "💦": "sweat drops",
  "☔": "umbrella rain",
  "☂️": "umbrella",
  "🌊": "wave ocean",
  "🍏": "apple green",
  "🍎": "apple red",
  "🍐": "pear",
  "🍊": "orange tangerine",
  "🍋": "lemon",
  "🍌": "banana",
  "🍉": "watermelon",
  "🍇": "grapes",
  "🍓": "strawberry",
  "🫐": "blueberry",
  "🍈": "melon",
  "🍒": "cherries",
  "🍑": "peach",
  "🥭": "mango",
  "🍍": "pineapple",
  "🥥": "coconut",
  "🥝": "kiwi",
  "🍅": "tomato",
  "🍆": "eggplant",
  "🥑": "avocado",
  "🥦": "broccoli",
  "🥬": "lettuce greens",
  "🥒": "cucumber",
  "🌶️": "pepper hot chili",
  "🫑": "pepper",
  "🌽": "corn",
  "🥕": "carrot",
  "🫒": "olive",
  "🧄": "garlic",
  "🧅": "onion",
  "🥔": "potato",
  "🍠": "sweet potato",
  "🥐": "croissant",
  "🥯": "bagel",
  "🍞": "bread",
  "🥖": "baguette",
  "🥨": "pretzel",
  "🧀": "cheese",
  "🥚": "egg",
  "🍳": "cooking egg",
  "🧈": "butter",
  "🥞": "pancakes",
  "🧇": "waffle",
  "🥓": "bacon",
  "🥩": "steak meat",
  "🍗": "chicken leg",
  "🍖": "meat",
  "🦴": "bone",
  "🌭": "hotdog",
  "🍔": "burger hamburger",
  "🍟": "fries",
  "🍕": "pizza",
  "🫓": "flatbread",
  "🥪": "sandwich",
  "🥙": "pita",
  "🧆": "falafel",
  "🌮": "taco",
  "🌯": "burrito",
  "🫔": "tamale",
  "🥗": "salad",
  "🥘": "paella pan",
  "🫕": "fondue",
  "🥫": "can",
  "🍝": "pasta spaghetti",
  "🍜": "ramen noodles",
  "🍲": "stew pot",
  "🍛": "curry",
  "🍣": "sushi",
  "🍱": "bento",
  "🥟": "dumpling",
  "🦪": "oyster",
  "🍤": "shrimp fried",
  "🍙": "rice ball",
  "🍚": "rice",
  "🍘": "rice cracker",
  "🍥": "fish cake",
  "🥠": "fortune cookie",
  "🥮": "moon cake",
  "🍢": "oden",
  "🍡": "dango",
  "🍧": "shaved ice",
  "🍨": "ice cream",
  "🍦": "soft serve",
  "🥧": "pie",
  "🧁": "cupcake",
  "🍰": "cake shortcake",
  "🎂": "birthday cake",
  "🍮": "custard",
  "🍭": "lollipop",
  "🍬": "candy",
  "🍫": "chocolate",
  "🍿": "popcorn",
  "🍩": "donut doughnut",
  "🍪": "cookie",
  "🌰": "chestnut",
  "🥜": "peanut",
  "🍯": "honey",
  "🥛": "milk",
  "🍼": "bottle baby",
  "🫖": "teapot",
  "☕": "coffee tea",
  "🍵": "tea",
  "🧃": "juice box",
  "🥤": "cup straw",
  "🧋": "boba bubble tea",
  "🍶": "sake",
  "🍺": "beer",
  "🍻": "beers cheers",
  "🥂": "champagne cheers",
  "🍷": "wine",
  "🥃": "whiskey tumbler",
  "🍸": "cocktail",
  "🍹": "tropical drink",
  "🧉": "mate",
  "🍾": "champagne",
  "🧊": "ice",
  "🥄": "spoon",
  "🍴": "fork knife",
  "🍽️": "plate dinner",
  "🥣": "bowl",
  "🥡": "takeout",
  "🥢": "chopsticks",
  "🧂": "salt",
  "⚽": "soccer football",
  "🏀": "basketball",
  "🏈": "football",
  "⚾": "baseball",
  "🥎": "softball",
  "🎾": "tennis",
  "🏐": "volleyball",
  "🏉": "rugby",
  "🥏": "frisbee",
  "🎱": "pool 8ball",
  "🪀": "yo-yo",
  "🏓": "ping pong",
  "🏸": "badminton",
  "🏒": "hockey ice",
  "🏑": "hockey field",
  "🥍": "lacrosse",
  "🏏": "cricket",
  "🪃": "boomerang",
  "🥅": "goal",
  "⛳": "golf",
  "🪁": "kite",
  "🏹": "bow arrow",
  "🎣": "fishing",
  "🤿": "diving",
  "🥊": "boxing",
  "🥋": "martial arts",
  "🎽": "running shirt",
  "🛹": "skateboard",
  "🛼": "roller skate",
  "🛷": "sled",
  "⛸️": "ice skate",
  "🎿": "skis",
  "🪂": "parachute",
  "🏆": "trophy win",
  "🥇": "gold medal first",
  "🥈": "silver medal",
  "🥉": "bronze medal",
  "🏅": "medal",
  "🎖️": "military medal",
  "🏵️": "rosette",
  "🎗️": "reminder ribbon",
  "🎫": "ticket",
  "🎟️": "tickets",
  "🎪": "circus",
  "🎭": "theater arts",
  "🩰": "ballet",
  "🎨": "art palette",
  "🎬": "clapper movie",
  "🎤": "mic microphone",
  "🎧": "headphones",
  "🎼": "score music",
  "🎹": "piano keys",
  "🥁": "drum",
  "🪘": "long drum",
  "🎷": "sax",
  "🎺": "trumpet",
  "🪗": "accordion",
  "🎸": "guitar",
  "🪕": "banjo",
  "🎻": "violin",
  "🎲": "dice",
  "♟️": "chess",
  "🎯": "dart target",
  "🎳": "bowling",
  "🎮": "game video",
  "🎰": "slot",
  "🧩": "puzzle",
  "🚗": "car",
  "🚕": "taxi",
  "🚙": "suv",
  "🚌": "bus",
  "🚎": "trolley",
  "🏎️": "race car",
  "🚓": "police car",
  "🚑": "ambulance",
  "🚒": "fire truck",
  "🚐": "van",
  "🛻": "truck pickup",
  "🚚": "truck",
  "🚛": "semi",
  "🚜": "tractor",
  "🦯": "cane",
  "🦽": "wheelchair",
  "🦼": "motor wheelchair",
  "🛴": "scooter",
  "🚲": "bike bicycle",
  "🛵": "scooter motor",
  "🏍️": "motorcycle",
  "🛺": "auto rickshaw",
  "🚨": "siren",
  "🚔": "police",
  "🚍": "bus",
  "🚘": "car",
  "🚖": "taxi",
  "🚡": "cable car",
  "🚠": "gondola",
  "🚟": "railway suspension",
  "🚃": "railway car",
  "🚋": "tram",
  "🚞": "mountain railway",
  "🚝": "monorail",
  "🚄": "bullet train",
  "🚅": "bullet train",
  "🚈": "light rail",
  "🚂": "locomotive",
  "🚆": "train",
  "🚇": "metro subway",
  "🚊": "tram",
  "🚉": "station",
  "✈️": "plane airplane",
  "🛫": "departure",
  "🛬": "arrival",
  "🛩️": "small plane",
  "💺": "seat",
  "🛰️": "satellite",
  "🚀": "rocket space",
  "🛸": "ufo",
  "🚁": "helicopter",
  "🛶": "canoe",
  "⛵": "sailboat",
  "🚤": "speedboat",
  "🛥️": "motorboat",
  "🛳️": "passenger ship",
  "⛴️": "ferry",
  "🚢": "ship",
  "⚓": "anchor",
  "⛽": "fuel",
  "🚧": "construction",
  "🚦": "traffic light",
  "🚥": "traffic light",
  "🗺️": "map",
  "🗿": "moai",
  "🗽": "liberty",
  "🗼": "tokyo tower",
  "🏰": "castle",
  "🏯": "castle japanese",
  "🏟️": "stadium",
  "🎡": "ferris wheel",
  "🎢": "coaster",
  "🎠": "carousel",
  "⛲": "fountain",
  "⛱️": "umbrella beach",
  "🏖️": "beach",
  "🏝️": "island",
  "🏜️": "desert",
  "🌋": "volcano",
  "⛰️": "mountain",
  "🏔️": "mountain snow",
  "🗻": "fuji",
  "🏕️": "camping",
  "⛺": "tent",
  "🏠": "house home",
  "🏡": "house garden",
  "🏘️": "houses",
  "🏚️": "derelict",
  "🏗️": "construction",
  "🏭": "factory",
  "🏢": "office",
  "🏬": "department",
  "🏣": "post office",
  "🏤": "post office",
  "🏥": "hospital",
  "🏦": "bank",
  "🏨": "hotel",
  "🏪": "convenience",
  "🏫": "school",
  "🏩": "love hotel",
  "💒": "wedding",
  "🏛️": "classical building",
  "⛪": "church",
  "🕌": "mosque",
  "🕍": "synagogue",
  "🛕": "hindu temple",
  "🕋": "kaaba",
  "⛩️": "shinto",
  "🛤️": "tracks",
  "🛣️": "motorway",
  "🗾": "japan map",
  "🎑": "moon viewing",
  "🏞️": "national park",
  "🌅": "sunrise",
  "🌄": "sunrise mountain",
  "🌠": "shooting star",
  "🎇": "sparkler",
  "🎆": "fireworks",
  "🌇": "sunset",
  "🌆": "city dusk",
  "🏙️": "cityscape",
  "🌃": "night",
  "🌌": "milky way",
  "🌉": "bridge night",
  "🌁": "foggy",
  "⌚": "watch",
  "📱": "phone mobile",
  "📲": "phone arrow",
  "💻": "laptop computer",
  "⌨️": "keyboard",
  "🖥️": "desktop",
  "🖨️": "printer",
  "🖱️": "mouse",
  "🖲️": "trackball",
  "🕹️": "joystick",
  "🗜️": "clamp",
  "💽": "minidisc",
  "💾": "floppy",
  "💿": "cd",
  "📀": "dvd",
  "📼": "vhs",
  "📷": "camera",
  "📸": "camera flash",
  "📹": "video camera",
  "🎥": "movie camera",
  "📽️": "film projector",
  "🎞️": "film",
  "📞": "phone",
  "☎️": "telephone",
  "📟": "pager",
  "📠": "fax",
  "📺": "tv",
  "📻": "radio",
  "🎙️": "studio mic",
  "🎚️": "level slider",
  "🎛️": "control knobs",
  "🧭": "compass",
  "⏱️": "stopwatch",
  "⏲️": "timer",
  "⏰": "alarm clock",
  "🕰️": "mantelpiece clock",
  "⌛": "hourglass",
  "⏳": "hourglass flowing",
  "📡": "satellite antenna",
  "🔋": "battery",
  "🔌": "plug",
  "💡": "bulb idea light",
  "🔦": "flashlight",
  "🕯️": "candle",
  "🪔": "diya",
  "🧯": "extinguisher",
  "🛢️": "oil",
  "💸": "money wings",
  "💵": "dollar",
  "💴": "yen",
  "💶": "euro",
  "💷": "pound",
  "🪙": "coin",
  "💰": "money bag",
  "💳": "credit card",
  "💎": "gem diamond",
  "⚖️": "scales justice",
  "🪜": "ladder",
  "🧰": "toolbox",
  "🪛": "screwdriver",
  "🔧": "wrench",
  "🔨": "hammer",
  "⚒️": "hammer pick",
  "🛠️": "hammer wrench",
  "⛏️": "pick",
  "🪚": "saw",
  "🔩": "nut bolt",
  "⚙️": "gear",
  "🪤": "mouse trap",
  "🧱": "brick",
  "⛓️": "chains",
  "🧲": "magnet",
  "🔫": "gun pistol",
  "💣": "bomb",
  "🧨": "firecracker",
  "🪓": "axe",
  "🔪": "knife",
  "🗡️": "dagger",
  "⚔️": "swords",
  "🛡️": "shield",
  "🚬": "cigarette",
  "⚰️": "coffin",
  "🪦": "headstone",
  "⚱️": "urn",
  "🏺": "amphora",
  "🔮": "crystal ball",
  "📿": "prayer beads",
  "🧿": "nazar",
  "💈": "barber",
  "⚗️": "alembic",
  "🔭": "telescope",
  "🔬": "microscope",
  "🕳️": "hole",
  "🩹": "bandage",
  "🩺": "stethoscope",
  "💊": "pill",
  "💉": "syringe",
  "🩸": "blood",
  "🧬": "dna",
  "🦠": "microbe virus",
  "🧫": "petri",
  "🧪": "test tube",
  "🌡️": "thermometer",
  "🧹": "broom",
  "🪠": "plunger",
  "🧺": "basket",
  "🧻": "paper roll",
  "🚽": "toilet",
  "🚰": "water",
  "🚿": "shower",
  "🛁": "bathtub",
  "🧼": "soap",
  "🪥": "toothbrush",
  "🪒": "razor",
  "🧽": "sponge",
  "🪣": "bucket",
  "🧴": "lotion",
  "🛎️": "bellhop",
  "🔑": "key",
  "🗝️": "old key",
  "🚪": "door",
  "🪑": "chair",
  "🛋️": "couch",
  "🛏️": "bed",
  "🧸": "teddy",
  "🪆": "nesting dolls",
  "🖼️": "frame",
  "🪞": "mirror",
  "🪟": "window",
  "🛍️": "bags",
  "🛒": "cart",
  "🎁": "gift present",
  "🎈": "balloon",
  "🎏": "carp streamer",
  "🎀": "ribbon",
  "🪄": "wand magic",
  "🪅": "pinata",
  "🎊": "confetti",
  "🎉": "party popper tada",
  "🎎": "dolls",
  "🏮": "lantern",
  "🎐": "wind chime",
  "🧧": "red envelope",
  "✉️": "envelope email",
  "📩": "envelope arrow",
  "📨": "incoming",
  "📧": "e-mail",
  "💌": "love letter",
  "📥": "inbox",
  "📤": "outbox",
  "📦": "package box",
  "🏷️": "label",
  "🪧": "placard",
  "📪": "mailbox",
  "📫": "mailbox",
  "📬": "mailbox",
  "📭": "mailbox",
  "📮": "postbox",
  "📯": "postal horn",
  "📜": "scroll",
  "📃": "page",
  "📄": "page",
  "📑": "bookmark tabs",
  "🧾": "receipt",
  "📊": "bar chart",
  "📈": "chart up",
  "📉": "chart down",
  "🗒️": "notepad",
  "🗓️": "calendar",
  "📆": "calendar",
  "📅": "calendar date",
  "🗑️": "wastebasket trash",
  "📇": "card index",
  "🗃️": "card box",
  "🗳️": "ballot",
  "🗄️": "file cabinet",
  "📋": "clipboard",
  "📁": "folder",
  "📂": "folder open",
  "🗂️": "dividers",
  "🗞️": "newspaper",
  "📰": "newspaper",
  "📓": "notebook",
  "📔": "notebook",
  "📒": "ledger",
  "📕": "book closed",
  "📗": "book green",
  "📘": "book blue",
  "📙": "book orange",
  "📚": "books",
  "📖": "book open",
  "🔖": "bookmark",
  "🧷": "safety pin",
  "🔗": "link",
  "📎": "paperclip",
  "🖇️": "paperclips",
  "📐": "triangle ruler",
  "📏": "ruler",
  "🧮": "abacus",
  "📌": "pushpin pin",
  "📍": "pin round",
  "✂️": "scissors",
  "🖊️": "pen",
  "🖋️": "fountain pen",
  "✒️": "nib",
  "🖌️": "brush",
  "🖍️": "crayon",
  "📝": "memo note pencil",
  "✏️": "pencil",
  "🔍": "search zoom",
  "🔎": "search zoom",
  "🔏": "lock pen",
  "🔐": "lock key",
  "🔒": "lock",
  "🔓": "unlock",
  "❤️": "heart love red",
  "🧡": "heart orange",
  "💛": "heart yellow",
  "💚": "heart green",
  "💙": "heart blue",
  "💜": "heart purple",
  "🖤": "heart black",
  "🤍": "heart white",
  "🤎": "heart brown",
  "💔": "heart broken",
  "❣️": "heart exclamation",
  "💕": "hearts",
  "💞": "hearts revolving",
  "💓": "heartbeat",
  "💗": "heart growing",
  "💖": "heart sparkle",
  "💘": "heart arrow",
  "💝": "heart ribbon",
  "💟": "heart decoration",
  "☮️": "peace",
  "✝️": "cross",
  "☪️": "star crescent",
  "🕉️": "om",
  "☸️": "dharma",
  "✡️": "star david",
  "🔯": "star six",
  "🕎": "menorah",
  "☯️": "yin yang",
  "☦️": "orthodox cross",
  "🛐": "worship",
  "⛎": "ophiuchus",
  "♈": "aries",
  "♉": "taurus",
  "♊": "gemini",
  "♋": "cancer",
  "♌": "leo",
  "♍": "virgo",
  "♎": "libra",
  "♏": "scorpio",
  "♐": "sagittarius",
  "♑": "capricorn",
  "♒": "aquarius",
  "♓": "pisces",
  "🆔": "id",
  "⚛️": "atom",
  "🉑": "accept",
  "☢️": "radioactive",
  "☣️": "biohazard",
  "📴": "phone off",
  "📳": "vibration",
  "🈶": "japanese",
  "🈚": "japanese",
  "🈸": "japanese",
  "🈺": "japanese",
  "🈷️": "japanese",
  "✴️": "star",
  "🆚": "vs",
  "💮": "white flower",
  "🉐": "bargain",
  "㊙️": "secret",
  "㊗️": "congratulations",
  "🈴": "passing",
  "🈵": "full",
  "🈹": "discount",
  "🈲": "prohibited",
  "🅰️": "a",
  "🅱️": "b",
  "🆎": "ab",
  "🆑": "cl",
  "🅾️": "o",
  "🆘": "sos",
  "❌": "x cross no",
  "⭕": "circle",
  "🛑": "stop",
  "⛔": "no entry",
  "📛": "name badge",
  "🚫": "prohibited no",
  "💯": "100 hundred",
  "💢": "anger",
  "♨️": "hotsprings",
  "🚷": "no pedestrians",
  "🚯": "no litter",
  "🚳": "no bicycles",
  "🚱": "no water",
  "🔞": "underage",
  "📵": "no phones",
  "🚭": "no smoking",
  "❗": "exclamation",
  "❕": "exclamation",
  "❓": "question",
  "❔": "question",
  "‼️": "exclamation",
  "⁉️": "exclamation question",
  "🔅": "dim",
  "🔆": "bright",
  "〽️": "part alternation",
  "⚠️": "warning",
  "🚸": "children crossing",
  "🔱": "trident",
  "⚜️": "fleur",
  "🔰": "beginner",
  "♻️": "recycle",
  "✅": "check yes",
  "🈯": "reserved",
  "💹": "chart yen",
  "❇️": "sparkle",
  "✳️": "eight spoke",
  "❎": "cross mark",
  "🌐": "globe meridians",
  "💠": "diamond",
  "Ⓜ️": "m",
  "🌀": "cyclone",
  "💤": "zzz sleep",
  "🏧": "atm",
  "🚾": "wc",
  "♿": "wheelchair",
  "🅿️": "parking",
  "🛗": "elevator",
  "🈳": "vacancy",
  "🈂️": "service",
  "🛂": "passport",
  "🛃": "customs",
  "🛄": "baggage",
  "🛅": "left luggage",
  "🚹": "mens",
  "🚺": "womens",
  "🚼": "baby",
  "⚧️": "transgender",
  "🚻": "restroom",
  "🚮": "litter",
  "🎦": "cinema",
  "📶": "signal",
  "🈁": "here",
  "🔣": "symbols",
  "ℹ️": "info",
  "🔤": "abc",
  "🔡": "abcd",
  "🔠": "abcd",
  "🆖": "ng",
  "🆗": "ok",
  "🆙": "up",
  "🆒": "cool",
  "🆕": "new",
  "🆓": "free",
  "0️⃣": "zero 0",
  "1️⃣": "one 1",
  "2️⃣": "two 2",
  "3️⃣": "three 3",
  "4️⃣": "four 4",
  "5️⃣": "five 5",
  "6️⃣": "six 6",
  "7️⃣": "seven 7",
  "8️⃣": "eight 8",
  "9️⃣": "nine 9",
  "🔟": "ten 10",
  "🔢": "numbers",
  "#️⃣": "hash pound",
  "*️⃣": "asterisk",
  "⏏️": "eject",
  "▶️": "play",
  "⏸️": "pause",
  "⏯️": "play pause",
  "⏹️": "stop",
  "⏺️": "record",
  "⏭️": "next",
  "⏮️": "previous",
  "⏩": "fast forward",
  "⏪": "rewind",
  "⏫": "fast up",
  "⏬": "fast down",
  "◀️": "reverse",
  "🔼": "up button",
  "🔽": "down button",
  "➡️": "right arrow",
  "⬅️": "left arrow",
  "⬆️": "up arrow",
  "⬇️": "down arrow",
  "↗️": "up right",
  "↘️": "down right",
  "↙️": "down left",
  "↖️": "up left",
  "↕️": "up down",
  "↔️": "left right",
  "↪️": "right hook",
  "↩️": "left hook",
  "⤴️": "right up",
  "⤵️": "right down",
  "🔀": "shuffle",
  "🔁": "repeat",
  "🔂": "repeat one",
  "🔄": "arrows circle",
  "🔃": "arrows clockwise",
  "🎵": "note music",
  "🎶": "notes music",
  "➕": "plus",
  "➖": "minus",
  "➗": "divide",
  "✖️": "multiply",
  "♾️": "infinity",
  "💲": "dollar",
  "💱": "currency",
  "™️": "tm trademark",
  "©️": "copyright",
  "®️": "registered",
  "👁️‍🗨️": "eye speech",
  "🔚": "end",
  "🔙": "back",
  "🔛": "on",
  "🔝": "top",
  "🔜": "soon",
  "〰️": "wave dash",
  "➰": "curl",
  "➿": "curly loop",
  "✔️": "check",
  "☑️": "ballot check",
  "🔘": "radio button",
  "🔴": "red circle",
  "🟠": "orange circle",
  "🟡": "yellow circle",
  "🟢": "green circle",
  "🔵": "blue circle",
  "🟣": "purple circle",
  "⚫": "black circle",
  "⚪": "white circle",
  "🟤": "brown circle",
  "🔺": "red triangle",
  "🔻": "red triangle down",
  "🔸": "diamond orange",
  "🔹": "diamond blue",
  "🔶": "diamond orange large",
  "🔷": "diamond blue large",
  "🔳": "button white",
  "🔲": "button black",
  "▪️": "square",
  "▫️": "square",
  "◾": "square",
  "◽": "square",
  "◼️": "square",
  "◻️": "square",
  "🟥": "red square",
  "🟧": "orange square",
  "🟨": "yellow square",
  "🟩": "green square",
  "🟦": "blue square",
  "🟪": "purple square",
  "⬛": "black square",
  "⬜": "white square",
  "🟫": "brown square",
  "🔈": "speaker",
  "🔇": "mute",
  "🔉": "speaker",
  "🔊": "speaker loud",
  "🔔": "bell",
  "🔕": "bell off",
  "📣": "megaphone",
  "📢": "loudspeaker",
  "💬": "speech",
  "💭": "thought",
  "🗯️": "anger bubble",
  "♠️": "spades",
  "♣️": "clubs",
  "♥️": "hearts",
  "♦️": "diamonds",
  "🃏": "joker",
  "🎴": "flower cards",
  "🀄": "mahjong",
  "🕐": "clock 1",
  "🕑": "clock 2",
  "🕒": "clock 3",
  "🕓": "clock 4",
  "🕔": "clock 5",
  "🕕": "clock 6",
  "🕖": "clock 7",
  "🕗": "clock 8",
  "🕘": "clock 9",
  "🕙": "clock 10",
  "🕚": "clock 11",
  "🕛": "clock 12",
  "🏳️": "flag white",
  "🏴": "flag black",
  "🏁": "flag checkered",
  "🚩": "flag triangular",
  "🏳️‍🌈": "pride rainbow flag",
  "🏳️‍⚧️": "trans flag",
  "🏴‍☠️": "pirate flag",
  "🇺🇸": "flag united states usa america",
  "🇬🇧": "flag uk britain england",
  "🇨🇦": "flag canada",
  "🇲🇽": "flag mexico",
  "🇧🇷": "flag brazil",
  "🇫🇷": "flag france",
  "🇩🇪": "flag germany",
  "🇮🇹": "flag italy",
  "🇪🇸": "flag spain",
  "🇯🇵": "flag japan",
  "🇨🇳": "flag china",
  "🇮🇳": "flag india",
  "🇰🇷": "flag korea",
  "🇦🇺": "flag australia",
};

const UNASSIGNED: [number, number][] = [
  [0x1f6d8, 0x1f6db],
  [0x1f6ed, 0x1f6ef],
  [0x1f6f9, 0x1f6ff],
  [0x1f7da, 0x1f7e0],
  [0x1f7ec, 0x1f7ef],
  [0x1f7f1, 0x1f7ff],
  [0x1f80c, 0x1f80f],
  [0x1f848, 0x1f84f],
  [0x1f85a, 0x1f85f],
  [0x1f888, 0x1f88f],
  [0x1f8ae, 0x1f8ff],
  [0x1fa6e, 0x1fa6f],
  [0x1fa7d, 0x1fa7f],
  [0x1fa8a, 0x1fa8f],
  [0x1faca, 0x1face],
  [0x1fadc, 0x1fadf],
  [0x1faea, 0x1faef],
  [0x1faf9, 0x1faff],
];

function isAssigned(codePoint: number): boolean {
  return !UNASSIGNED.some(([start, end]) => codePoint >= start && codePoint <= end);
}

function isEmojiChar(value: string): boolean {
  try {
    return /\p{Extended_Pictographic}/u.test(value);
  } catch {
    return true;
  }
}

function toEmoji(codePoint: number): string {
  const base = String.fromCodePoint(codePoint);
  if (codePoint < 0x10000) return `${base}\uFE0F`;
  return base;
}

function categoryOf(codePoint: number): string {
  if (
    (codePoint >= 0x1f600 && codePoint <= 0x1f64f) ||
    (codePoint >= 0x1f910 && codePoint <= 0x1f92f) ||
    (codePoint >= 0x1f970 && codePoint <= 0x1f97f) ||
    (codePoint >= 0x1fae0 && codePoint <= 0x1faef) ||
    (codePoint >= 0x1f90c && codePoint <= 0x1f90f) ||
    codePoint === 0x2639 ||
    codePoint === 0x263a
  ) {
    return "smileys";
  }
  if (
    (codePoint >= 0x1f440 && codePoint <= 0x1f4aa) ||
    (codePoint >= 0x1f466 && codePoint <= 0x1f487) ||
    (codePoint >= 0x1f9b0 && codePoint <= 0x1f9b9) ||
    (codePoint >= 0x1f9d0 && codePoint <= 0x1f9df) ||
    (codePoint >= 0x1fac0 && codePoint <= 0x1faff) ||
    (codePoint >= 0x1f574 && codePoint <= 0x1f57a) ||
    (codePoint >= 0x270a && codePoint <= 0x270d) ||
    codePoint === 0x261d
  ) {
    return "people";
  }
  if (
    (codePoint >= 0x1f400 && codePoint <= 0x1f43f) ||
    (codePoint >= 0x1f980 && codePoint <= 0x1f9ae) ||
    (codePoint >= 0x1f330 && codePoint <= 0x1f343) ||
    (codePoint >= 0x1f344 && codePoint <= 0x1f353) ||
    (codePoint >= 0x1f54a && codePoint <= 0x1f54a) ||
    (codePoint >= 0x1f577 && codePoint <= 0x1f578) ||
    (codePoint >= 0x1f30d && codePoint <= 0x1f32c) ||
    (codePoint >= 0x2600 && codePoint <= 0x26c8)
  ) {
    return "animals";
  }
  if (
    (codePoint >= 0x1f32d && codePoint <= 0x1f37f) ||
    (codePoint >= 0x1f950 && codePoint <= 0x1f96f) ||
    (codePoint >= 0x1f9c0 && codePoint <= 0x1f9cb) ||
    (codePoint >= 0x1fad0 && codePoint <= 0x1fadf)
  ) {
    return "food";
  }
  if (
    (codePoint >= 0x1f680 && codePoint <= 0x1f6ff) ||
    (codePoint >= 0x1f5fa && codePoint <= 0x1f5ff) ||
    (codePoint >= 0x1f3d4 && codePoint <= 0x1f3f0) ||
    (codePoint >= 0x1f301 && codePoint <= 0x1f30c) ||
    codePoint === 0x2708
  ) {
    return "travel";
  }
  if (
    (codePoint >= 0x1f3a0 && codePoint <= 0x1f3d3) ||
    (codePoint >= 0x1f3f8 && codePoint <= 0x1f3ff) ||
    (codePoint >= 0x1f93c && codePoint <= 0x1f94f) ||
    (codePoint >= 0x26bd && codePoint <= 0x26be) ||
    (codePoint >= 0x1f947 && codePoint <= 0x1f94b)
  ) {
    return "activities";
  }
  if (
    (codePoint >= 0x1f4a0 && codePoint <= 0x1f4ff) ||
    (codePoint >= 0x1f50d && codePoint <= 0x1f5c4) ||
    (codePoint >= 0x1f9e0 && codePoint <= 0x1f9ff) ||
    (codePoint >= 0x1fa80 && codePoint <= 0x1fa9f) ||
    (codePoint >= 0x1fa70 && codePoint <= 0x1fa7c)
  ) {
    return "objects";
  }
  if (codePoint >= 0x1f1e6 && codePoint <= 0x1f1ff) return "flags";
  if (codePoint === 0x1f3c1 || codePoint === 0x1f6a9 || codePoint === 0x1f38c) return "flags";
  return "symbols";
}

function flagEmoji(code: string): string {
  return [...code.toUpperCase()]
    .map((letter) => String.fromCodePoint(0x1f1e6 + letter.charCodeAt(0) - 65))
    .join("");
}

function unique(values: string[]): string[] {
  return [...new Set(values)];
}

const generated: Record<string, string[]> = Object.fromEntries(
  EMOJI_CATEGORIES.map((category) => [category.id, [] as string[]]),
);

for (const [start, end] of RANGES) {
  for (let codePoint = start; codePoint <= end; codePoint += 1) {
    if (codePoint >= 0x1f3fb && codePoint <= 0x1f3ff) continue;
    if (codePoint >= 0x1f1e6 && codePoint <= 0x1f1ff) continue;
    if (!isAssigned(codePoint)) continue;
    const emoji = toEmoji(codePoint);
    if (!isEmojiChar(emoji)) continue;
    generated[categoryOf(codePoint)].push(emoji);
  }
}

for (const extra of EXTRA) {
  const first = [...extra][0] ?? extra;
  const codePoint = first.codePointAt(0) ?? 0;
  generated[categoryOf(codePoint)].push(extra);
}

generated.flags.push(...ISO_FLAGS.map(flagEmoji));

export const EMOJIS_BY_CATEGORY: Record<string, string[]> = Object.fromEntries(
  Object.entries(generated).map(([id, list]) => [id, unique(list)]),
);

export const ALL_EMOJIS = unique(Object.values(EMOJIS_BY_CATEGORY).flat());

export function filterEmojis(query: string, category: string): string[] {
  const needle = query.trim().toLowerCase();
  const pool = needle ? ALL_EMOJIS : (EMOJIS_BY_CATEGORY[category] ?? ALL_EMOJIS);
  if (!needle) return pool;
  return pool.filter((emoji) => {
    if (emoji.includes(query.trim())) return true;
    const names = KEYWORDS[emoji];
    return names ? names.includes(needle) : false;
  });
}
